name: Rotina de Cobranca NTFY

on:
  schedule:
    # Roda todos os dias às 08:00 da manhã (Horário de Brasília)
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  verificar-vencimentos:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar pacote do Firebase
        run: npm install firebase

      - name: Rodar a varredura
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        run: node check-cobranca.mjs
